name: Update GitHub Mirror

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  update_mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update mirror
        run: |
          git remote add mirror https://git.yoctoproject.org/meta-xilinx
          git push mirror --mirror
