name: Update GitHub Mirror

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes    
    # - cron: '0 * * * *' # Runs every hour

jobs:
  update_mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update local from upstream
        run: |
          git remote add upstream https://git.yoctoproject.org/meta-xilinx
          git remote -v
          git fetch upstream
          git fetch --tags
          git push origin --mirror 
